-- MySQL Script generated by MySQL Workbench
-- Thu Mar 24 23:46:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema examen2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema examen2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `examen2` DEFAULT CHARACTER SET utf8 ;
USE `examen2` ;

-- -----------------------------------------------------
-- Table `examen2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examen2`.`usuario` (
  `Codigo` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(35) NULL,
  `Rol` VARCHAR(20) NULL,
  `Clave` VARCHAR(15) NULL,
  `EstaActivo` TINYINT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `examen2`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examen2`.`producto` (
  `Codigo` VARCHAR(30) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Precio` DECIMAL(18,2) NULL,
  `Existencia` INT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `examen2`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examen2`.`pedido` (
  `Codigo` INT NOT NULL AUTO_INCREMENT,
  `NombreCliente` VARCHAR(40) NULL,
  `Fecha` TIMESTAMP NULL,
  `Cantidad` INT NULL,
  `Precio` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
